# requirements.yaml
dependencies:
- name: centralledger
  version: 5.2.0
  repository: "file://../centralledger"
  condition: centralledger.enabled
- name: interop-switch-js
  version: 3.4.2
  repository: "file://../interop-switch-js"
  condition: interop-switch-js.enabled
- name: ml-api-adapter
  version: 5.2.0
  repository: "file://../ml-api-adapter"
  condition: ml-api-adapter.enabled
- name: routing
  version: 0.1.0
  repository: "file://../routing"
  condition: routing.enabled