# requirements.yaml
dependencies:
- name: central
  version: 3.7.7
  repository: "file://../central"
  condition: central.enabled
- name: interop-switch
  version: 3.4.2
  repository: "file://../interop-switch"
  condition: interop-switch.enabled
- name: ml-api-adapter
  version: 3.7.5
  repository: "file://../ml-api-adapter"
  condition: ml-api-adapter.enabled
