apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  name: hn-nodes-custom
  namespace: test
spec:
  ingress:
  - from:
    - ipBlock:
        cidr: 10.42.0.0/24
  podSelector: {}
  policyTypes:
  - Ingress
