# requirements.yaml
dependencies:
- name: fluentd-elasticsearch
  version: 4.3.2
  repository: "https://kiwigrid.github.io"
  condition: fluentd-elasticsearch.enabled
- name: elasticsearch
  version: 7.2.1-0
  repository: "https://helm.elastic.co"
  condition: elasticsearch.enabled
- name: kibana
  version: 7.2.1-0
  repository: "https://helm.elastic.co"
  condition: kibana.enabled
- name: apm-server
  version: 2.1.4
  repository: "https://kubernetes-charts.storage.googleapis.com/"
  condition: apm-server.enabled
